version: "3.9"
services:
  db:
    image: postgres:16
    container_name: leafside_db
    environment:
      POSTGRES_USER: leafuser
      POSTGRES_PASSWORD: leafpass
      POSTGRES_DB: leafsidedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U leafuser -d leafsidedb"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  pgdata:
